feat: Add support for Terraform 0.13
AlaskaAirlines/generator-aag-terraform-module pull request #10
Opened 2020-11-04 22:53 UTC by nweddle

2020-11-06 16:55 UTC, tsalright requested changes
Everything looks good, but I wonder why we only support 11 or 13 terraform and completely removed 12. Either we support 11, 12, and 13. Or Lastest - 1 (12 and 13). Or just latest (13).

2020-11-06 16:55 UTC, tsalright commented on generators/app/index.js
>              name: '0.11',
Why are we leaving version 11 in there? If we removed 12, can we remove 11 too and just force everything to be 13?

2020-11-06 16:55 UTC, tsalright commented on generators/app/templates/.terraform-version
> +<% if (tfVersion == '11') { %>latest:^0.11<% } -%>
Same as previous question. Why remove 12 if we offer 11 and 13. Shouldn't we offer 11, 12, and 13? Or should we just offer 12 and 13? Or just 13?

2020-11-06 16:55 UTC, tsalright commented on generators/app/templates/examples/main.tf
> +<% if (tfVersion == '11') { %>  input     = "${var.input}"<% } %><% if (tfVersion == '13') { %>  input     = var.input<% } %>
Same about the whole 11, 12, 13 as other comments.

2020-11-06 16:55 UTC, tsalright commented on generators/app/templates/examples/versions.tf
> +<% if (tfVersion == '11') { %>  required_version = "< 0.12"<% } %><% if (tfVersion == '13') { %>  required_version = ">= 0.13"<% } %>
Same as the 11, 12, 13 comments.

2020-11-06 16:55 UTC, tsalright commented on generators/app/templates/variables.tf
> +<% if (tfVersion == '11') { %>  type        = "string"<% } %><% if (tfVersion == '13') { %>  type        = string<% } %>
11, 12, 13 terraform support?

2020-11-07 00:07 UTC, nweddle commented
> Everything looks good, but I wonder why we only support 11 or 13 terraform and completely removed 12. Either we support 11, 12, and 13. Or Lastest - 1 (12 and 13). Or just latest (13).

Apologies, my thinking should have been explained in the PR comment, I will add the below to it.

I propose keeping support for Terraform 11 and for the most recent stable version (13), potentially removing support for 11 in a later PR.

My reasoning has to do with the underlying version of HCL (HashiCorp Configuration Language) used by these versions. Terraform 11 is the last version to support HCL 1, with 13 (and 12) supporting HCL 2. See [1] for more.

This affects Terraform authors in two ways. Not only is there a breaking change in the syntax of Terraform code written for 11 versus that written for 13, there remains a significant difference in the underlying version of the Terraform Plugin SDK used to build Terraform providers targeting those different versions.

Legacy providers that have traditionally worked with versions of Terraform 11 and below will not function with Terraform 13 (or 12) unless the maintainers refactor their plug-in to support the newer version. Not all maintainers have done this yet and we may have need of these older providers, potentially.

There are indeed differences between Terraform 12 and 13[2], however these differences are not as great as those between Terraform 11 and 12[3]. If a Terraform author wishes to develop a new module that supports modern versions, they should skip ahead to 13, thus removing any need of us to generate version 12 modules.

[1] https://github.com/hashicorp/hcl/wiki/HCL-2.0-Transition
[2] https://www.terraform.io/upgrade-guides/0-13.html
[3] https://www.terraform.io/upgrade-guides/0-12.html

2020-11-09 17:23 UTC, tsalright approved these changes

2020-11-09 17:23 UTC, merged

2020-11-09 17:32 UTC, AutomationPlatforms commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/AlaskaAirlines/generator-aag-terraform-module/releases/tag/v1.2.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairgroup/generator-aag-terraform-module/v/1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: